apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  database-name: c2FtcGxlZGI=
  database-password: cGFzc3dvcmQ=
  database-root-password: cGFzc3dvcmQ=
  database-user: bXlzcWw=
